package net.danh.sinceDungeon.api.interfaces;

import org.bukkit.Location;
import org.bukkit.World;

import java.util.concurrent.CompletableFuture;

/**
 * Interface defining the strict contract for Dungeon World Instancing.
 * Implementing this allows developers to replace standard Bukkit world generation
 * with advanced, lag-free solutions like SlimeWorldManager or AdvancedSlimePaper.
 */
public interface InstanceProvider {

    void initialize();

    void cleanup();

    /**
     * Asynchronously creates a new world instance from a template.
     *
     * @param templateName The name of the source template world/folder.
     * @param instanceId   The generated unique ID for the new instance.
     * @return A CompletableFuture returning the loaded World.
     */
    CompletableFuture<World> createInstance(String templateName, String instanceId);

    /**
     * Returns the coordinate origin assigned to a specific dungeon instance.
     * Full-world providers keep the origin at 0,0,0; shared-world providers can offset
     * every action into an isolated pasted schematic region.
     *
     * @param instanceId The unique dungeon instance ID generated by the core.
     * @param world      The Bukkit world returned by createInstance.
     * @return The local coordinate origin for this instance.
     */
    default Location getInstanceOrigin(String instanceId, World world) {
        return world != null ? new Location(world, 0, 0, 0) : null;
    }

    /**
     * Returns the default spawn point for this instance.
     * Shared schematic providers should return a location inside the allocated region,
     * not the global shared-world spawn.
     *
     * @param instanceId The unique dungeon instance ID generated by the core.
     * @param world      The Bukkit world returned by createInstance.
     * @return The entry spawn location for the dungeon party.
     */
    default Location getInstanceSpawnLocation(String instanceId, World world) {
        return world != null ? world.getSpawnLocation().clone().add(0.5, 1, 0.5) : null;
    }

    /**
     * Returns the region radius owned by this instance.
     * A value below 1 means the provider owns the whole returned world.
     *
     * @param instanceId The unique dungeon instance ID generated by the core.
     * @return The half-size radius used for event routing in shared worlds.
     */
    default int getInstanceRadius(String instanceId) {
        return -1;
    }

    /**
     * Indicates whether multiple dungeon instances can share the same Bukkit world.
     *
     * @return true if this provider allocates isolated regions inside a shared world.
     */
    default boolean isSharedWorld() {
        return false;
    }

    /**
     * Releases an instance after normal completion or failure.
     * Full-world providers unload/delete the world; shared-world providers clear only
     * the allocated schematic region and reuse the world.
     *
     * @param instanceId The unique dungeon instance ID generated by the core.
     * @param world      The world returned by createInstance.
     */
    default void releaseInstance(String instanceId, World world) {
        unloadAndDeleteInstance(world);
    }

    /**
     * Safely unloads and permanently deletes the given world instance.
     *
     * @param world The world to delete.
     */
    void unloadAndDeleteInstance(World world);

    /**
     * Force-releases an instance during shutdown.
     * The default keeps the old full-world behavior for existing providers.
     *
     * @param instanceId The unique dungeon instance ID generated by the core.
     * @param world      The world returned by createInstance.
     */
    default void forceReleaseInstance(String instanceId, World world) {
        forceUnloadAndDeleteInstance(world);
    }

    /**
     * Forcefully unloads and deletes the world, ignoring active players (used for server shutdown).
     *
     * @param world The world to delete.
     */
    void forceUnloadAndDeleteInstance(World world);
}
