name: SinceDungeon
version: '1.0'
main: net.danh.sinceDungeon.SinceDungeon
api-version: '1.20'
authors: [ VoChiDanh ]
website: https://gitlab.com/sincerpg/SinceDungeon/-/wikis/home
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    MMOItems:
      load: BEFORE
      required: false
    MythicLib:
      load: BEFORE
      required: false
    WorldGuard:
      load: BEFORE
      required: false
    MythicMobs:
      load: BEFORE
      required: false
permissions:
  SinceDungeon.admin:
    description: Admin permission for SinceDungeon
    default: op