name: SinceDungeon-PremiumAddon
version: '${version}'
main: net.danh.sincedungeonpremium.SinceDungeonPremium
api-version: '1.21'
authors: [ VoChiDanh ]
website: https://gitlab.com/sincerpg/SinceDungeon/-/wikis/home
dependencies:
  server:
    SinceDungeon:
      load: BEFORE
      required: true
    DecentHolograms:
      load: BEFORE
      required: false
    MMOCore:
      load: BEFORE
      required: false